// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF_bBWqmv6EdTRc64hOXO4VZN-d-9OjvE',
    appId: '1:881634082553:web:fcd92659104e5dc9152c28',
    messagingSenderId: '881634082553',
    projectId: 'quizapp-sai',
    authDomain: 'quizapp-sai.firebaseapp.com',
    databaseURL: 'https://quizapp-sai-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quizapp-sai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtT_MpNnTwHFAvXnVgEErmtea7DwpGBUY',
    appId: '1:881634082553:android:f3cc95a9c996a5b9152c28',
    messagingSenderId: '881634082553',
    projectId: 'quizapp-sai',
    databaseURL: 'https://quizapp-sai-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quizapp-sai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYTNCnJD8vTT_E0NTZSWM2iOvPMtogCT4',
    appId: '1:881634082553:ios:97da84db5eeebcb7152c28',
    messagingSenderId: '881634082553',
    projectId: 'quizapp-sai',
    databaseURL: 'https://quizapp-sai-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quizapp-sai.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

}